lvfs/shards/routes.py
#!/usr/bin/python3
# -*- coding: utf-8 -*-
#
# Copyright (C) 2019 Richard Hughes <richard@hughsie.com>
#
# SPDX-License-Identifier: GPL-2.0+

from collections import defaultdict
from typing import Dict

from uuid import UUID

from celery.schedules import crontab

from flask import (
    Blueprint,
    flash,
    make_response,
    redirect,
    render_template,
    request,
    url_for,
)
from flask_login import login_required

from lvfs import db, tq

from lvfs.components.models import (
    Component,
    ComponentShard,
    ComponentShardClaim,
    ComponentShardInfo,
)
from lvfs.claims.models import Claim
from lvfs.util import admin_login_required

from .utils import _async_regenerate_shard_infos

bp_shards = Blueprint("shards", __name__, template_folder="templates")


@tq.on_after_finalize.connect
def setup_periodic_tasks(sender, **_):
    sender.add_periodic_task(
        crontab(hour=3, minute=0),
        _async_regenerate_shard_infos.s(),
    )


@bp_shards.route("/")
@login_required
@admin_login_required
def route_list():

    # only show shards with the correct group_id
    shards = (
        db.session.query(ComponentShardInfo)
        .order_by(ComponentShardInfo.cnt.desc())
        .all()
    )
    return render_template("shard-list.html", category="admin", shards=shards)


@bp_shards.route("/create", methods=["POST"])
@login_required
@admin_login_required
def route_create():
    # ensure has enough data
    if "guid" not in request.form:
        flash("No form data found", "warning")
        return redirect(url_for("shards.route_list"))
    guid = request.form["guid"].lower()
    try:
        _ = UUID(guid)
    except ValueError:
        flash("Failed to add shard: Not a GUID", "warning")
        return redirect(url_for("shards.route_list"))

    # already exists
    if (
        db.session.query(ComponentShardInfo)
        .filter(ComponentShardInfo.guid == guid)
        .first()
    ):
        flash("Failed to add shard: Already exists", "info")
        return redirect(url_for("shards.route_list"))

    # add ComponentShardInfo
    info = ComponentShardInfo(guid=guid)
    db.session.add(info)
    db.session.commit()
    flash("Added shard", "info")
    return redirect(
        url_for(
            "shards.route_show", component_shard_info_id=info.component_shard_info_id
        )
    )


@bp_shards.route("/<int:component_shard_info_id>/modify", methods=["POST"])
@login_required
@admin_login_required
def route_modify(component_shard_info_id):

    # find shard
    shard = (
        db.session.query(ComponentShardInfo)
        .filter(ComponentShardInfo.component_shard_info_id == component_shard_info_id)
        .first()
    )
    if not shard:
        flash("No shard found", "info")
        return redirect(url_for("shards.route_list"))

    # modify shard
    for key in ["description", "claim_id"]:
        if key in request.form:
            setattr(shard, key, request.form[key] or None)
    db.session.commit()

    # success
    flash("Modified shard", "info")
    return route_show(component_shard_info_id)


@bp_shards.route("/<int:component_shard_info_id>/details")
@login_required
@admin_login_required
def route_show(component_shard_info_id):

    # find shard
    shard = (
        db.session.query(ComponentShardInfo)
        .filter(ComponentShardInfo.component_shard_info_id == component_shard_info_id)
        .first()
    )
    if not shard:
        flash("No shard found", "info")
        return redirect(url_for("shards.route_list"))

    # show details
    claims = db.session.query(Claim).order_by(Claim.summary).all()
    return render_template(
        "shard-details.html", category="admin", claims=claims, shard=shard
    )


@bp_shards.route("/<int:component_shard_info_id>/components")
@login_required
@admin_login_required
def route_components(component_shard_info_id):

    # find shard
    shard_info = (
        db.session.query(ComponentShardInfo)
        .filter(ComponentShardInfo.component_shard_info_id == component_shard_info_id)
        .first()
    )
    if not shard_info:
        flash("No shard found", "info")
        return redirect(url_for("shards.route_list"))

    # get shards with a unique component appstream ID
    shards = (
        db.session.query(ComponentShard)
        .join(ComponentShardInfo)
        .filter(ComponentShardInfo.component_shard_info_id == component_shard_info_id)
        .join(Component)
        .distinct(Component.appstream_id)
        .order_by(Component.appstream_id, ComponentShard.name.desc())
        .all()
    )
    unique_mds: Dict[str, Component] = defaultdict(list)
    for shard in shards:
        if shard.md not in unique_mds[shard.name]:
            unique_mds[shard.name].append(shard.md)

    # show details
    return render_template(
        "shard-components.html",
        category="admin",
        unique_mds=unique_mds,
        shard=shard_info,
    )


@bp_shards.route("/<int:component_shard_info_id>/checksums")
@login_required
@admin_login_required
def route_checksums(component_shard_info_id):

    # find shard
    shard_info = (
        db.session.query(ComponentShardInfo)
        .filter(ComponentShardInfo.component_shard_info_id == component_shard_info_id)
        .first()
    )
    if not shard_info:
        flash("No shard found", "info")
        return redirect(url_for("shards.route_list"))

    # get shards with a unique component appstream ID
    shards_by_checksum: Dict[str, ComponentShard] = defaultdict(list)
    for shard in (
        db.session.query(ComponentShard)
        .join(ComponentShardInfo)
        .filter(ComponentShardInfo.component_shard_info_id == component_shard_info_id)
    ):
        shards_by_checksum[shard.checksum].append(shard)

    # show details
    return render_template(
        "shard-checksums.html",
        category="admin",
        shards_by_checksum=shards_by_checksum,
        shard=shard_info,
    )


@bp_shards.route("/<int:component_shard_info_id>/claims")
@login_required
@admin_login_required
def route_claims(component_shard_info_id):

    # find shard
    shard = (
        db.session.query(ComponentShardInfo)
        .filter(ComponentShardInfo.component_shard_info_id == component_shard_info_id)
        .first()
    )
    if not shard:
        flash("No shard found", "info")
        return redirect(url_for("shards.route_list"))

    # get claims for this ComponentShardInfo
    claims = (
        db.session.query(ComponentShardClaim)
        .filter(ComponentShardClaim.component_shard_info_id == component_shard_info_id)
        .all()
    )

    # show details
    claims_all = db.session.query(Claim).order_by(Claim.summary).all()
    return render_template(
        "shard-claims.html",
        category="admin",
        claims=claims,
        claims_all=claims_all,
        shard=shard,
    )


@bp_shards.route(
    "/<int:component_shard_info_id>/claim/<int:component_shard_claim_id>/delete",
    methods=["POST"],
)
@login_required
@admin_login_required
def route_shard_claim_delete(component_shard_info_id, component_shard_claim_id):

    # find shard
    shard_claim = (
        db.session.query(ComponentShardClaim)
        .filter(ComponentShardClaim.component_shard_info_id == component_shard_info_id)
        .filter(
            ComponentShardClaim.component_shard_claim_id == component_shard_claim_id
        )
        .first()
    )
    if not shard_claim:
        flash("No shard claim found", "info")
        return redirect(url_for("shards.route_list"))
    db.session.delete(shard_claim)
    db.session.commit()
    flash("Deleted shard claim", "info")
    return redirect(
        url_for("shards.route_claims", component_shard_info_id=component_shard_info_id)
    )


@bp_shards.route("/<int:component_shard_info_id>/claim/create", methods=["POST"])
@login_required
@admin_login_required
def route_shard_claim_create(component_shard_info_id):

    # ensure has enough data
    for key in ["checksum", "claim_id"]:
        if key not in request.form:
            flash("No {} form data found!".format(key), "warning")
            return redirect(url_for("shards.route_list"))

    # already exists
    if (
        db.session.query(ComponentShardClaim)
        .filter(ComponentShardClaim.component_shard_info_id == component_shard_info_id)
        .filter(ComponentShardClaim.checksum == request.form["checksum"])
        .first()
    ):
        flash(
            "Failed to add component shard claim: The checksum already exists", "info"
        )
        return redirect(url_for("issues.route_list"))

    # add issue
    claim = ComponentShardClaim(
        component_shard_info_id=component_shard_info_id,
        checksum=request.form["checksum"],
        claim_id=request.form["claim_id"],
    )
    db.session.add(claim)
    db.session.commit()
    flash("Added claim", "info")
    return redirect(
        url_for("shards.route_claims", component_shard_info_id=component_shard_info_id)
    )


@bp_shards.route("/<int:component_shard_id>/download")
@login_required
@admin_login_required
def route_download(component_shard_id):

    # find shard
    shard = (
        db.session.query(ComponentShard)
        .filter(ComponentShard.component_shard_id == component_shard_id)
        .first()
    )
    if not shard:
        flash("No shard found", "info")
        return redirect(url_for("shards.route_list"))
    if not shard.md.fw.check_acl("@view"):
        flash("Permission denied: Unable to download shard", "danger")
        return redirect(url_for("main.route_dashboard"))
    if not shard.blob:
        flash("Permission denied: Shard has no data", "warning")
        return redirect(url_for("main.route_dashboard"))
    response = make_response(shard.blob)
    response.headers.set("Content-Type", "application/octet-stream")
    response.headers.set(
        "Content-Disposition",
        "attachment",
        filename="{}-{}".format(shard.guid, shard.checksum),
    )
    return response

lvfs/shards/templates/shard-checksums.html
{% extends "default.html" %}
{% block title %}Component Shard Checksums{% endblock %}

{% block nav %}{% include 'shard-nav.html' %}{% endblock %}

{% block content %}

{% for checksum in shards_by_checksum %}
{% set shards = shards_by_checksum[checksum] %}
<div class="card mt-3">
  <div class="card-body">
    <h2 class="card-title"><code>{{checksum}}</code></h2>
    <ul class="list-group">
{% for shard in shards|sort(attribute='name_with_vendor') %}
{% set md = shard.md %}
{% set remote = md.fw.remote %}
      <li class="list-group-item">
        <a href="{{url_for('components.route_show', component_id=md.component_id)}}">
          {{md.name_with_vendor}} &mdash; {{md.version_display}}
          <img class="fa float-right" src="{{url_for('cdn', filename='img/' + remote.icon_name + '-solid.svg')}}" width="16"
            alt="{{remote.name}}"
            title="{{remote.description}}"/>
        </a>
      </li>
{% endfor %}
    </ul>
    <a class="card-link btn btn-info mt-3"
       href="{{url_for('shards.route_download', component_shard_id=shards[0].component_shard_id)}}">
      Download File
{% if shard.size %}
      ({{format_size(shard.size)}})
{% endif %}
    </a>
  </div>
</div>
{% endfor %}

{% endblock %}

lvfs/shards/templates/shard-claims.html
{% extends "default.html" %}
{% block title %}Component Shard Claims{% endblock %}

{% block nav %}{% include 'shard-nav.html' %}{% endblock %}

{% block content %}

<div class="card">
  <div class="card-body">
    <h2 class="card-title">Component Shard Claims</h2>
<table class="table">
  <tr class="row">
    <th class="col col-sm-6">Checksum</th>
    <th class="col col-sm-4">Claim</th>
    <th class="col col-sm-2">&nbsp;</th>
  </tr>
{% if claims|length == 0 %}
  <tr class="row">
    <td class="col col-sm-12"><p class="text-muted">No claims exist yet.</p></td>
  </tr>
</p>
{% else %}
{% for claim in claims|sort(attribute='checksum') %}
  <tr class="row">
    <td class="col col-sm-6"><code>{{claim.checksum|truncate(64, False, '…')}}</code></td>
    <td class="col col-sm-4"><code>{{claim.claim.summary}}</code></td>
    <td class="col col-sm-2">
      <form action="{{url_for('shards.route_shard_claim_delete',
                              component_shard_info_id=claim.component_shard_info_id,
                              component_shard_claim_id=claim.component_shard_claim_id)}}" method="POST">
        <input type="hidden" name="csrf_token" value="{{csrf_token()}}"/>
        <button class="btn-block btn btn-danger">Delete</button>
      </form>
    </td>
  </tr>
{% endfor %}
{% endif %}
  <tr class="row">
    <form method="post" action="{{url_for('shards.route_shard_claim_create',
                                          component_shard_info_id=shard.component_shard_info_id)}}">
    <input type="hidden" name="csrf_token" value="{{csrf_token()}}"/>
    <td class="col col-sm-6">
      <input type="text" class="form-control" name="checksum" value="" placeholder="Checksum..." required>
    </td>
    <td class="col col-sm-4">
    <select class="form-control" name="claim_id">
{% for claim in claims_all %}
      <option value="{{claim.claim_id}}">{{claim.summary}}</option>
{% endfor %}
    </select>
    </td>
    <td class="col col-sm-2">
      <input type="submit" class="btn btn-block btn-primary" value="Add">
    </td>
    </form>
  </tr>
</table>
  </div>
</div>

{% endblock %}

lvfs/shards/templates/shard-components.html
{% extends "default.html" %}
{% block title %}Component Shard Components{% endblock %}

{% block nav %}{% include 'shard-nav.html' %}{% endblock %}

{% block content %}

{% for appstream_id in unique_mds %}
<div class="card mt-3">
  <div class="card-body">
    <h2 class="card-title"><code>{{appstream_id}}</code></h2>
    <ul class="list-group">
{% for md in unique_mds[appstream_id]|sort(attribute='name_with_vendor') %}
      <li class="list-group-item">{{md.name_with_vendor}}</li>
{% endfor %}
    </ul>
  </div>
</div>
{% endfor %}

{% endblock %}

lvfs/shards/templates/shard-details.html
{% extends "default.html" %}
{% block title %}Component Shard Details{% endblock %}

{% block nav %}{% include 'shard-nav.html' %}{% endblock %}

{% block content %}
<div class="card">
  <div class="card-body">
    <h2 class="card-title">Component Shard Details</h2>
<form method="post" action="{{url_for('shards.route_modify', component_shard_info_id=shard.component_shard_info_id)}}">
  <input type="hidden" name="csrf_token" value="{{csrf_token()}}"/>
  <div class="form-group">
    <label for="description">Description:</label>
    <textarea class="form-control" id="description" name="description" rows="10">{{shard.description if shard.description}}</textarea>
  </div>
  <div class="form-group">
    <label for="claim_id">GUID Claim:</label>
    <select class="form-control" id="claim_id" name="claim_id">
      <option value="" {{ 'selected' if shard.claim_id == 0 }}>None</option>
{% for claim in claims %}
      <option value="{{claim.claim_id}}" {{ 'selected' if shard.claim_id == claim.claim_id }}>{{claim.summary}}</option>
{% endfor %}
    </select>
  </div>
  <input type="submit" class="card-link btn btn-primary" value="Save">
</form>
  </div>
</div>

{% endblock %}

lvfs/shards/templates/shard-list.html
{% extends "default.html" %}
{% block title %}Component Shards{% endblock %}

{% block content %}

{% if shards|length == 0 %}
<div class="card">
  <div class="card-body">
    <p class="card-text text-secondary">
      No shards have been created.
    </p>
  </div>
</div>

{% else %}

{% for shard in shards %}
<div class="card mt-3">
  <div class="card-body">
    <h2 class="card-title">
      <code>{{shard.guid}}</code> ({{shard.cnt}})
    </h2>
    <div class="card-text mb-3">
{% if shard.description %}
      {{shard.description}}
{% else %}
      No description!
{% endif %}
    </div>
    <a class="card-link btn btn-info"
      href="{{url_for('shards.route_show', component_shard_info_id=shard.component_shard_info_id)}}"
      role="button">Details</a>
    <a class="card-link btn btn-info"
      href="{{url_for('firmware.route_shard_search', kind='guid', value=shard.guid)}}"
      role="button">Firmware</a>
  </div>
</div>
{% endfor %}

{% endif %}

<div class="card mt-3">
  <div class="card-body">
    <h2 class="card-title">Create a new shard</h2>
    <form method="post" action="{{url_for('shards.route_create')}}" class="form">
      <input type="hidden" name="csrf_token" value="{{csrf_token()}}"/>
      <div class="form-group card-text">
        <label for="guid">GUID</label>
        <input class="form-control" type="text" id="guid" name="guid" placeholder="9b3ada4f-ae56-4c24-8dea-f03b7558ae50" required />
      </div>
      <input class="card-link btn btn-primary" type="submit" value="Add"/>
    </form>
  </div>
</div>

{% endblock %}

lvfs/shards/templates/shard-nav.html
<nav>
  <div class="text-center mb-3">
    <div class="btn-group" role="group">
      <a class="btn btn-falcon-{{'primary' if request.url_rule.endpoint == 'shards.route_show' else 'default'}}"
        href="{{url_for('shards.route_show', component_shard_info_id=shard.component_shard_info_id)}}">Details</a>
      <a class="btn btn-falcon-{{'primary' if request.url_rule.endpoint == 'shards.route_components' else 'default'}}"
        href="{{url_for('shards.route_components', component_shard_info_id=shard.component_shard_info_id)}}">Components</a>
      <a class="btn btn-falcon-{{'primary' if request.url_rule.endpoint == 'shards.route_checksums' else 'default'}}"
        href="{{url_for('shards.route_checksums', component_shard_info_id=shard.component_shard_info_id)}}">Variants</a>
      <a class="btn btn-falcon-{{'primary' if request.url_rule.endpoint == 'shards.route_claims' else 'default'}}"
        href="{{url_for('shards.route_claims', component_shard_info_id=shard.component_shard_info_id)}}">Checksum Claims</a>
    </div>
  </div>
</nav>