lvfs/docs/routes.py
#!/usr/bin/python3
# -*- coding: utf-8 -*-
#
# Copyright (C) 2015 Richard Hughes <richard@hughsie.com>
#
# SPDX-License-Identifier: GPL-2.0+
#
# pylint: disable=wrong-import-position,singleton-comparison

from flask import Blueprint, redirect, render_template

from lvfs import app, db

from lvfs.agreements.models import Agreement
from lvfs.protocols.models import Protocol
from lvfs.vendors.models import Vendor
from lvfs.verfmts.models import Verfmt

bp_docs = Blueprint("docs", __name__, template_folder="templates")


@app.route("/developers")  # deprecated
@bp_docs.route("/developers")
def route_developers():
    return render_template("docs-developers.html")


@app.route("/privacy")  # deprecated
@bp_docs.route("/privacy")
def route_privacy():
    return redirect("https://lvfs.readthedocs.io/en/latest/privacy.html", code=302)


@app.route("/users")  # deprecated
@bp_docs.route("/users")
def route_users():
    return render_template("docs-users.html")


@bp_docs.route("/lvfs/news")
def route_news():
    return redirect("https://lvfs.readthedocs.io/en/latest/news.html", code=302)


@app.route("/vendors")
@bp_docs.route("/vendors")
def route_vendors():
    return render_template("docs-vendors.html")


@bp_docs.route("/metainfo/version")
def route_metainfo_version():
    verfmts = db.session.query(Verfmt).order_by(Verfmt.verfmt_id.asc()).all()
    return render_template(
        "docs-metainfo-version.html", category="documentation", verfmts=verfmts
    )


@bp_docs.route("/metainfo/protocol")
def route_metainfo_protocol():
    protocols = db.session.query(Protocol).order_by(Protocol.protocol_id.asc()).all()
    return render_template(
        "docs-metainfo-protocol.html", category="documentation", protocols=protocols
    )


@app.route("/metainfo")  # deprecated
@bp_docs.route("/composite")
@bp_docs.route("/metainfo")
@bp_docs.route("/metainfo/category")
@bp_docs.route("/metainfo/intro")
@bp_docs.route("/metainfo/restrict")
@bp_docs.route("/metainfo/style")
@bp_docs.route("/metainfo/urls")
def route_metainfo():
    return redirect("https://lvfs.readthedocs.io/en/latest/metainfo.html", code=302)


@bp_docs.route("/archive")
@bp_docs.route("/affiliates")
def route_archive():
    return redirect("https://lvfs.readthedocs.io/en/latest/upload.html", code=302)


@bp_docs.route("/telemetry")
def route_telemetry():
    return redirect("https://lvfs.readthedocs.io/en/latest/telemetry.html", code=302)


@bp_docs.route("/introduction")
def route_introduction():
    return redirect("https://lvfs.readthedocs.io/en/latest/intro.html", code=302)


@bp_docs.route("/agreement")
def route_agreement():
    agreement = db.session.query(Agreement).order_by(Agreement.version.desc()).first()
    return render_template(
        "docs-agreement.html", category="documentation", agreement=agreement
    )


@bp_docs.route("/consulting")
def route_consulting():
    vendors = (
        db.session.query(Vendor)
        .filter(Vendor.consulting_text != None)
        .order_by(Vendor.display_name.desc())
        .all()
    )
    return render_template(
        "docs-consulting.html", category="documentation", vendors=vendors
    )


@bp_docs.route("/consulting/info")
def route_consulting_info():
    return render_template("docs-consulting-info.html", category="documentation")

lvfs/templates/50x.html
<!DOCTYPE html>
<!-- Copyright (C) 2018 Richard Hughes <richard@hughsie.com>
     SPDX-License-Identifier: GPL-2.0+ -->
<html lang="en">
  <head>
    <title>LVFS: Temporarily Unavailable</title>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
    <link rel="stylesheet" href="{{url_for('cdn', filename='theme.css')}}"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  </head>
  <body>
    <div class="container">
      <div class="row flex-center text-center min-vh-100">
        <div class="col-sm-11 col-md-9 col-lg-7 col-xl-6 col-xxl-5"><a class="d-block text-center mb-4" href="/">
            <div class="d-inline-flex flex-center">
              <img class="mr-2" src="{{url_for('cdn', filename='avatar.png')}}" alt="" width="58" />
              <span class="text-sans-serif font-weight-extra-bold fs-5 d-inline-block">LVFS</span>
            </div>
          </a>
          <div class="card">
            <div class="card-body p-5">
              <p class="lead mt-4 text-800 text-sans-serif font-weight-semi-bold">Something went wrong!</p>
              <hr />
              <p class="card-text">
                Try refreshing the page, or going back and attempting the action again.
                If this problem persists, <a href="mailto:{{admin_email}}">contact us</a>.
              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
</html>

lvfs/templates/base.html
<!DOCTYPE html>
<!-- Copyright (C) 2015 Richard Hughes <richard@hughsie.com>
     SPDX-License-Identifier: GPL-2.0+ -->
<html lang="en">
  <head>
    <title>LVFS: {% block title %}{% endblock %}</title>
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
    <link rel="stylesheet" href="{{url_for('cdn', filename='theme.css')}}">
    <link rel="stylesheet" href="{{url_for('static', filename='style.css')}}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{{url_for('cdn', filename='favicon.ico')}}"/>
{% block head %}
{% endblock %}
  </head>
  <body>
    <main class="main" id="top">
{% block body %}
{% endblock %}
    </main>

<script src="{{url_for('cdn', filename='jquery-3.5.1.slim.min.js')}}"></script><!-- https://code.jquery.com/jquery-3.5.1.slim.min.js -->
<script src="{{url_for('cdn', filename='popper.min.js')}}"></script><!-- https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js -->
<script src="{{url_for('cdn', filename='bootstrap.min.js')}}"></script><!-- https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js -->
<script src="{{url_for('cdn', filename='theme.js')}}"></script>
{% block script %}
{% endblock %}
  </body>
</html>

lvfs/templates/default.html
{% if g.user is defined and g.user %}
{% extends "private.html" %}
{% else %}
{% extends "public.html" %}
{% endif %}

lvfs/templates/error-401.html
{% extends "default.html" %}

{% block title %}Permission denied{% endblock %}

{% block content %}
<div class="row flex-center min-vh-100 py-6 text-center">
  <div class="col-sm-10 col-md-8 col-lg-6 col-xxl-5">
    <div class="card">
      <div class="card-body p-4 p-sm-5">
        <div class="display-1 text-200 fs-error">401</div>
        <p class="lead mt-4 text-800 text-sans-serif font-weight-semi-bold">
          Permission denied: {{msg}}
        </p>
        <hr/>
        <p>
          Make sure the address is correct and that your user account is allowed access to this resource.
          If you think this is a mistake please <a href="mailto:{{admin_email}}">contact us</a> or your LVFS vendor manager.
        </p>
        <a class="btn btn-primary btn-sm mt-3" href="{{url_for('main.route_index')}}">
          <img class="fa" src="{{url_for('cdn', filename='img/home-solid.svg')}}" width="16px" height="16px" />
          Back Home
        </a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

lvfs/templates/error-404.html
{% extends "default.html" %}

{% block title %}Permission denied{% endblock %}

{% block content %}
<div class="row flex-center min-vh-100 py-6 text-center">
  <div class="col-sm-10 col-md-8 col-lg-6 col-xxl-5">
    <div class="card">
      <div class="card-body p-4 p-sm-5">
        <div class="display-1 text-200 fs-error">404</div>
        <p class="lead mt-4 text-800 text-sans-serif font-weight-semi-bold">
          The page you're looking for is not found.
        </p>
        <hr/>
        <p>
          Make sure the address is correct and that the page hasn't moved.
          If you think this is a mistake please <a href="mailto:{{admin_email}}">contact us</a>.
        </p>
        <a class="btn btn-primary btn-sm mt-3" href="{{url_for('main.route_index')}}">
          <img class="fa" src="{{url_for('cdn', filename='img/home-solid.svg')}}" width="16px" height="16px" />
          Back Home
        </a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

lvfs/templates/error.html
{% extends "default.html" %}

{% block title %}Error{% endblock %}

{% block content %}
<div class="card">
  <div class="card-body">
    <h2 class="card-title">Error!</h2>
  </div>
</div>

        <div class="row flex-center min-vh-100 py-6 text-center">
          <div class="col-sm-10 col-md-8 col-lg-6 col-xxl-5">
            <div class="card">
              <div class="card-body p-4 p-sm-5">
                <div class="display-1 text-200 fs-error">404</div>
                <p class="lead mt-4 text-800 text-sans-serif font-weight-semi-bold">The page you're looking for is not found.</p>
                <hr />
                <p>
                  Make sure the address is correct and that the page hasn't moved.
                  If you think this is a mistake, <a href="mailto:{{admin_email}}">contact us</a>.
                </p>
                <a class="btn btn-primary btn-sm mt-3" href="../../index.html">
                  <img class="fa" src="{{url_for('cdn', filename='img/home-solid.svg')}}" width="16px" height="16px" />
                  Take me home
                </a>
              </div>
            </div>
          </div>
        </div>

{% endblock %}

lvfs/templates/public.html
{% extends "base.html" %}
{% block body %}

<!-- navigation -->
{% if request.url_rule.endpoint == 'index' %}
<nav class="navbar navbar-dark fs--1 font-weight-semi-bold navbar-standard navbar-theme navbar-expand-lg fixed-top">
{% else %}
<nav class="navbar navbar-dark fs--1 font-weight-semi-bold bg-dark navbar-expand-lg">
{% endif %}
  <div class="container">
    <a class="navbar-brand" href="/">
      <div class="d-flex align-items-center text-primary">
        <span class="text-white">LVFS</span>
      </div>
    </a>
    <button class="navbar-toggler collapsed" type="button" data-toggle="collapse" data-target="#navbarStandard" aria-controls="navbarStandard" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarStandard">
      <ul class="navbar-nav align-items-center">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" id="navbarDropdownPages" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Home
          </a>
          <div class="dropdown-menu dropdown-menu-card" aria-labelledby="navbarDropdownPages">
            <div class="bg-white rounded-soft py-2">
              <a class="dropdown-item" href="{{url_for('firmware.route_new')}}">New Firmware</a>
              <a class="dropdown-item" href="{{url_for('devices.route_list')}}">Supported Devices</a>
              <a class="dropdown-item" href="{{url_for('vendors.route_list')}}">Vendor List</a>
              <a class="dropdown-item" href="{{url_for('vendors.route_prodcerts')}}">Product Certification</a>
              <a class="dropdown-item" href="{{url_for('docs.route_privacy')}}">Privacy Report</a>
            </div>
          </div>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" id="navbarDropdownDocumentation" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Documentation
          </a>
          <div class="dropdown-menu dropdown-menu-card" aria-labelledby="navbarDropdownDocumentation">
            <div class="bg-white rounded-soft py-2">
              <a class="dropdown-item" href="{{url_for('docs.route_vendors')}}">Hardware Vendors</a>
              <a class="dropdown-item" href="{{url_for('docs.route_users')}}">End Users</a>
              <a class="dropdown-item" href="{{url_for('docs.route_developers')}}">Developers</a>
              <a class="dropdown-item" href="{{url_for('docs.route_introduction')}}">External Documentation</a>
              <div class="dropdown-divider"></div>
              <a class="dropdown-item" href="{{url_for('docs.route_agreement')}}">Vendor Agreement</a>
              <a class="dropdown-item" href="{{url_for('docs.route_consulting')}}">Consulting</a>
            </div>
          </div>
        </li>
      </ul>

      <ul class="navbar-nav align-items-center d-none d-lg-block ml-3">
        <li class="nav-item">
          <form class="form-inline search-box" action="{{url_for('search.route_search')}}">
            <input class="form-control" type="search" placeholder="Search for firmware..." name="value" aria-label="Search" style="background: none;"/>
          </form>
        </li>
      </ul>

      <ul class="navbar-nav align-items-center ml-auto">
{% if g.user is defined and g.user %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" id="navbarDropdownProfile" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Profile
          </a>
          <div class="dropdown-menu dropdown-menu-card" aria-labelledby="navbarDropdownProfile">
            <div class="bg-white rounded-soft py-2">
              <a class="dropdown-item" href="{{url_for('main.route_dashboard')}}">Dashboard</a>
              <a class="dropdown-item" href="{{url_for('main.route_profile')}}">User</a>
{% if g.user.vendor.check_acl('@manage-users') %}
              <a class="dropdown-item" href="{{url_for('vendors.route_users', vendor_id=g.user.vendor_id)}}">Vendor</a>
{% endif %}
{% if g.user.check_acl('@view-eventlog') %}
              <a class="dropdown-item" href="{{url_for('main.route_eventlog')}}">Events</a>
{% endif %}
              <a class="dropdown-item" href="{{url_for('main.route_logout')}}">Log Out</a>
            </div>
          </div>
        </li>
{% else %}
        <li class="nav-item">
          <a class="btn btn-sm btn-falcon-default" href="{{url_for('main.route_login1')}}" role="button">
            Login
          </a>
        </li>
{% endif %}
      </ul>
    </div>
  </div>
</nav>

{% block content2 %}
<div class="container mt-3">
{% for category, msg in get_flashed_messages(with_categories=true) %}
<div class="alert alert-{{ category }}" role="alert">
  {{ msg }}
</div>
{% endfor %}
{% block nav %}{% endblock %}
{% block content %}
{% endblock %}
</div>
{% endblock %}

<!-- footer -->
<section class="py-0 py-3">
  <div class="container">
    <div class="row justify-content-between fs--1">
      <div class="col-12 col-sm-auto">
        <p class="mb-0">
          <a class="text-700" href="https://{{g.container_id}}#{{g.release}}">LVFS</a>
          by <a class="text-700" href="mailto:richard@hughsie.com">Richard Hughes</a> &copy; 2015-2022
          with icons from <a href="https://fontawesome.com/license">Font Awesome</a>.
        </p>
        <p class="mb-0">
          Linux Vendor Firmware Service Project a Series of LF Projects, LLC
          :: <a class="text-700" href="https://gitlab.com/fwupd/lvfs-website/raw/master/docs/technical-charter.pdf">Charter</a>
        </p>
        <p class="mb-0">
        </p>
      </div>
    </div>
  </div>
</section>

{% endblock %}