lvfs/devices/routes.py
#!/usr/bin/python3
# -*- coding: utf-8 -*-
#
# Copyright (C) 2017 Richard Hughes <richard@hughsie.com>
#
# SPDX-License-Identifier: GPL-2.0+
#
# pylint: disable=consider-using-dict-items

import datetime
from typing import Dict, List, Any

from flask import Blueprint, render_template, flash, redirect, url_for, g, make_response
from flask_login import login_required

from sqlalchemy import func, or_
from sqlalchemy.orm.exc import NoResultFound

from uswid import uSwidIdentity

from lvfs import db

from lvfs.util import admin_login_required
from lvfs.devices.models import Product
from lvfs.categories.models import Category
from lvfs.firmware.models import Firmware
from lvfs.components.utils import _build_swid_identity_root
from lvfs.components.models import Component, ComponentGuid, ComponentShard
from lvfs.vendors.models import Vendor
from lvfs.metadata.models import Remote

bp_devices = Blueprint("devices", __name__, template_folder="templates")


@bp_devices.route("/status")
@bp_devices.route("/status/<int:vendor_id>")
@bp_devices.route("/status/<int:vendor_id>/<int:category_id>")
@login_required
def route_status(vendor_id=None, category_id=None):

    # fall back to the current vendor
    if not vendor_id:
        vendor = g.user.vendor
    else:
        try:
            vendor = (
                db.session.query(Vendor).filter(Vendor.vendor_id == vendor_id).one()
            )
        except NoResultFound:
            flash("No vendor with ID {} exists".format(vendor_id), "danger")
            return redirect(url_for("devices.route_status"))

    # find all the components uploaded by the vendor
    appstream_ids: Dict[str, Dict[str, Component]] = {}
    md_by_id: Dict[str, Component] = {}
    cats_by_id: Dict[int, Category] = {}
    for md in (
        db.session.query(Component)
        .join(Firmware)
        .filter(
            or_(
                Firmware.vendor == vendor,
                Firmware.odm_vendors.contains(vendor),
            )
        )
        .join(Remote)
        .filter(Remote.name != "deleted")
    ):

        # permission check
        if not md.fw.check_acl("@view"):
            continue

        # build available categories
        if md.category_id:
            cats_by_id[md.category_id] = md.category

        # filter
        if category_id:
            if category_id != md.category_id:
                continue

        # put something human readable in the UI
        md_by_id[md.appstream_id] = md

        # appstream ID not yet added
        md_by_remote = appstream_ids.get(md.appstream_id)
        if not md_by_remote:
            appstream_ids[md.appstream_id] = {md.fw.remote.key: md}
            continue

        # remote not yet added
        old_md = md_by_remote.get(md.fw.remote.key)
        if not old_md:
            md_by_remote[md.fw.remote.key] = md
            continue

        # replace with newer version
        if md > old_md:
            md_by_remote[md.fw.remote.key] = md

    return render_template(
        "device-status.html",
        category="firmware",
        cats=cats_by_id.values(),
        vendor=vendor,
        category_id=category_id,
        appstream_ids=appstream_ids,
        md_by_id=md_by_id,
    )


@bp_devices.post("/state/<int:component_id>/<state>")
@login_required
def route_device_state(component_id, state):

    # get component
    md = (
        db.session.query(Component)
        .filter(Component.component_id == component_id)
        .first()
    )
    if not md:
        flash("No component with ID {} exists".format(component_id), "danger")
        return redirect(url_for(".route_status"))

    # permission check
    if not md.fw.check_acl("@modify"):
        flash("No permissions to modify component {}".format(component_id), "danger")
        return redirect(url_for(".route_status"))

    # encode into None
    if state == "active":
        state = Product.STATE_ACTIVE

    # ensure the model exists
    product = md.product
    if not product:
        product = Product(appstream_id=md.appstream_id)
        db.session.add(product)

    # all done
    product.state = state
    product.user = g.user
    product.mtime = datetime.datetime.utcnow()
    db.session.commit()
    flash("Product updated", "info")
    return redirect(url_for(".route_status"))


@bp_devices.route("/status/csv")
@bp_devices.route("/status/csv/<int:vendor_id>")
@bp_devices.route("/status/csv/<int:vendor_id>/<int:category_id>")
@login_required
def route_status_csv(vendor_id=None, category_id=None):

    # fall back to the current vendor
    if not vendor_id:
        vendor = g.user.vendor
    else:
        try:
            vendor = (
                db.session.query(Vendor).filter(Vendor.vendor_id == vendor_id).one()
            )
        except NoResultFound:
            flash("No vendor with ID {} exists".format(vendor_id), "danger")
            return redirect(url_for("devices.route_status"))

    # find all the components uploaded by the vendor
    appstream_ids: Dict[str, Dict[str, Component]] = {}
    md_by_id: Dict[str, Component] = {}
    for md in (
        db.session.query(Component)
        .join(Firmware)
        .filter(
            or_(
                Firmware.vendor == vendor.vendor,
                Firmware.odm_vendors.contains(vendor),
            )
        )
        .join(Remote)
        .filter(Remote.name != "deleted")
    ):

        # permission check
        if not md.fw.check_acl("@view"):
            continue

        # filter
        if category_id:
            if category_id != md.category_id:
                continue

        # put something human readable in the UI
        md_by_id[md.appstream_id] = md

        # appstream ID not yet added
        md_by_remote = appstream_ids.get(md.appstream_id)
        if not md_by_remote:
            appstream_ids[md.appstream_id] = {md.fw.remote.key: md}
            continue

        # remote not yet added
        old_md = md_by_remote.get(md.fw.remote.key)
        if not old_md:
            md_by_remote[md.fw.remote.key] = md
            continue

        # replace with newer version
        if md > old_md:
            md_by_remote[md.fw.remote.key] = md

    # header
    csv: List[str] = []
    remote_names: List[str] = ["private", "embargo", "testing", "stable"]
    csv.append(
        ",".join(["appstream_id", "model"] + remote_names + ["vendor_odm", "user"])
    )
    for appstream_id in sorted(appstream_ids):
        md_by_remote = appstream_ids[appstream_id]
        csv_line: List[str] = []
        csv_line.append(appstream_id)
        csv_line.append('"{}"'.format(md_by_id[appstream_id].name_with_vendor))
        md_best = None
        for remote_id in remote_names:
            md = md_by_remote.get(remote_id)
            if md:
                md_best = md
            csv_line.append(md.version_display if md else "")
        if md_best:
            try:
                group_id = md_best.fw.odm_vendors[0].group_id
            except IndexError:
                group_id = md_best.fw.vendor.group_id
            csv_line.append(group_id)
            csv_line.append(md_best.fw.user.username)
        else:
            csv_line.append("")
            csv_line.append("")
        csv.append(",".join(csv_line))

    response = make_response("\n".join(csv))
    response.headers.set("Content-Type", "text/csv")
    response.headers.set(
        "Content-Disposition", "attachment", filename="device-status.csv"
    )
    return response


@bp_devices.route("/admin")
@login_required
@admin_login_required
def route_list_admin():
    """
    Show all devices -- probably only useful for the admin user.
    """

    # get all the appstream_ids we can target
    devices: List[str] = []
    seen_appstream_id: Dict[str, bool] = {}
    for fw in db.session.query(Firmware):
        for md in fw.mds:
            if md.appstream_id in seen_appstream_id:
                continue
            seen_appstream_id[md.appstream_id] = True
            devices.append(md.appstream_id)

    return render_template("devices.html", devices=devices)


def _dt_from_quarter(year: int, quarter: int) -> Any:
    month = (quarter * 3) + 1
    if month > 12:
        month %= 12
        year += 1
    return datetime.datetime(year, month, 1)


def _get_fws_for_appstream_id(value):

    # old, deprecated GUID view
    if len(value.split("-")) == 5:
        return (
            db.session.query(Firmware)
            .join(Remote)
            .filter(Remote.is_public)
            .join(Component)
            .join(ComponentGuid)
            .filter(ComponentGuid.value == value)
            .order_by(Firmware.timestamp.desc())
            .all()
        )

    # new, AppStream ID view
    return (
        db.session.query(Firmware)
        .join(Remote)
        .filter(Remote.is_public)
        .join(Component)
        .filter(Component.appstream_id == value)
        .order_by(Firmware.timestamp.desc())
        .all()
    )


@bp_devices.route("/<appstream_id>")
def route_show(appstream_id):
    """
    Show information for one device, which can be seen without a valid login
    """
    fws = _get_fws_for_appstream_id(appstream_id)

    # work out the previous version for the shard diff
    fw_old = None
    fw_previous: Dict[Firmware, Firmware] = {}
    for fw in fws:
        if fw_old:
            fw_previous[fw_old] = fw
        fw_old = fw

    return render_template(
        "device.html", appstream_id=appstream_id, fws=fws, fw_previous=fw_previous
    )


@bp_devices.route("/<appstream_id>/atom")
def route_show_atom(appstream_id):
    """
    Show information for one device, which can be seen without a valid login
    """
    fws = _get_fws_for_appstream_id(appstream_id)
    return render_template("device-atom.xml", appstream_id=appstream_id, fws=fws)


@bp_devices.route("/component/<int:component_id>")
def route_shards(component_id):
    """
    Show information for one firmware, which can be seen without a valid login
    """

lvfs/devices/templates/device-analytics.html
{% extends "default.html" %}
{% block title %}Device{% endblock %}

{% block nav %}{% include 'device-nav.html' %}{% endblock %}

{% block content %}
<div class="card">
  <div class="card-body">
    <h2 class="card-title">{{fws[0].md_prio.name}}</h2>

<p class="card-text">This page show all the firmware releases in each quarter.</p>

<script src="{{url_for('cdn', filename='Chart.js')}}"></script>
<script>
Chart.defaults.global.animation = false;
</script>
<canvas id="ChartDevice" width="1000" height="400"></canvas>
  </div>
</div>
<script>
var ctx = document.getElementById("ChartDevice").getContext("2d");
var data = {
    labels: {{labels|safe}},
    datasets: [
        {
            label: "Firmware",
            borderColor: "rgba(20,120,220,0.2)",
            backgroundColor: "rgba(20,120,220,0.2)",
            data: {{data|safe}}
        },
    ]
};

new Chart(ctx, {
    type: 'bar',
    data: data,
    options: {
        scales: {
            yAxes: [{
                ticks: {
                    fixedStepSize: 1
                }
            }],
        },
        legend: {
            display: false
        }
    }
});

</script>

{% endblock %}

lvfs/devices/templates/device-new.html
{% extends "default.html" %}
{% block title %}New Devices{% endblock %}

{% block nav %}
<nav class="row">
  <div class="col col-sm-1 btn-group mb-3">
    <a class="btn btn-falcon-default mr-sm-3"
      href="{{url_for('devices.route_list')}}">
      <img class="fa" src="{{url_for('cdn', filename='img/arrow-left-solid.svg')}}" width="16px" height="16px" />
    </a>
  </div>
</nav>
{% endblock %}

{% block content %}

<!-- news -->
{% if devices|length > 0 %}
<div class="card mt-3">
  <div class="card-body">
    <h2 class="card-title">Latest Devices Supported</h2>
    <p class="card-text">
      This list shows the 30 newest devices supported by the LVFS.
    </p>
    <ul class="list-group">
{% for fw in devices %}
      <li class="list-group-item">
        <a href="{{url_for('devices.route_show', appstream_id=fw.md_prio.appstream_id)}}">{{fw.md_prio.name}}</a>
        was released by {{fw.vendor.display_name}} {{format_humanize_naturaltime(fw.release_ts)}}.
        <img class="float-right" src="/uploads/{{fw.vendor.icon}}" width="32"/>
      </li>
{% endfor %}
    </ul>
  </div>
</div>
{% endif %}

{% endblock %}

lvfs/devices/templates/device-status.html
{% extends "default.html" %}
{% block title %}Device Status{% endblock %}

{% block content %}
<div class="card">
  <div class="card-body">
    <h2 class="card-title">Device Status uploaded by {{vendor.display_name_with_team}}</h2>
{% if cats|length > 1 %}
    <div class="dropdown float-left">
      <button class="card-link btn btn-secondary dropdown-toggle"
              type="button" id="dropdownMenu1" data-toggle="dropdown"
              aria-haspopup="true" aria-expanded="false">
        Filter
      </button>
      <div class="dropdown-menu" aria-labelledby="dropdownMenu1">
        <a class="dropdown-item"
           href="{{url_for('devices.route_status', category_id=0, vendor_id=vendor.vendor_id)}}">
          None
        </a>
{% for cat in cats %}
        <a class="dropdown-item"
           href="{{url_for('devices.route_status', category_id=cat.category_id, vendor_id=vendor.vendor_id)}}">
          {{cat.name}}
        </a>
{% endfor %}
      </div>
    </div>
{% endif %}
    <div class="float-right">
      <a class="card-link btn btn-info"
         href="{{url_for('devices.route_status_csv', category_id=category_id, vendor_id=vendor.vendor_id)}}">
        Export as CSV
      </a>
    </div>
  </div>
</div>

<div class="card mt-3">
  <div class="card-body">
{% if not appstream_ids %}
    <p class="card-text">No devices to show!</p>
{% else %}
    <table class="table card-text">
      <tr class="row table-borderless">
        <th class="col col-sm-6">Model</th>
        <th class="col col-sm-1">Private</th>
        <th class="col col-sm-1">Embargo</th>
        <th class="col col-sm-1">Testing</th>
        <th class="col col-sm-1">Stable</th>
        <th class="col col-sm-2">&nbsp;</th>
      </tr>
{% for appstream_id in appstream_ids|sort %}
{% set md_by_remote = appstream_ids[appstream_id] %}
<tr class="row">
  <td class="col col-sm-6">
    <h5>
      {% set md = md_by_id[appstream_id] %}
      {{md.name_with_vendor}}
    </h5>
    <code class="text-muted">{{appstream_id}}</code>
{% set product = md.product %}
{% if product and product.state %}
    <p class="text-muted mt-3">
      Set as {{product.state_display}} {{format_humanize_naturaltime(product.mtime)}} by <code>{{product.user.username}}</code>
    </p>
{% endif %}
  </td>
{% for remote_id in ['private', 'embargo', 'testing', 'stable'] %}
  <td class="col col-sm-1">
    {% set md = md_by_remote.get(remote_id) %}
{% if md %}
    <a href="{{url_for('firmware.route_show', firmware_id=md.fw.firmware_id)}}">
      {{md.version_display}}
    </a>
{% else %}
      —
{% endif %}
  </td>
{% endfor %}

  <td class="col col-sm-2">
    {% set product = md_by_id[appstream_id].product %}
    <a class="btn btn-info btn-block" href="{{url_for("search.route_fw", value=appstream_id)}}">Show All</a>
{% if product and product.state != None %}
    <form action="{{url_for('devices.route_device_state', component_id=md.component_id, state="active")}}" method="POST">
      <input type="hidden" name="csrf_token" value="{{csrf_token()}}"/>
      <button class="mt-2 btn btn-warning btn-block">Mark Active</button>
    </form>
{% else %}
    <form action="{{url_for('devices.route_device_state', component_id=md.component_id, state="eol")}}" method="POST">
      <input type="hidden" name="csrf_token" value="{{csrf_token()}}"/>
      <button class="mt-2 btn btn-danger btn-block">Mark EOL</button>
    </form>
{% endif %}
  </td>

</tr>
{% endfor %}
    </table>

{% endif %}
  </div>
</div>
{% endblock %}

lvfs/devices/templates/device-swids.html
{% extends "default.html" %}
{% block title %}Firmware SWIDs{% endblock %}

{% block nav %}
<nav class="row">
  <div class="col col-sm-1 btn-group mb-3">
    <a class="btn btn-falcon-default mr-sm-3"
      href="{{url_for('devices.route_show', appstream_id=md.appstream_id)}}">
      <img class="fa" src="{{url_for('cdn', filename='img/arrow-left-solid.svg')}}" width="16px" height="16px" />
    </a>
  </div>
</nav>
{% endblock %}

{% block content %}

<div class="card">
  <div class="card-body">
    <h2 class="card-title">Software Bill of Materials</h2>
    <p class="card-text">
      The list below may be incomplete if the vendor has not supplied the required data.
    </p>
  </div>
</div>

{% for identity in identities %}

<div class="card mt-3">
  <div class="card-body">
    <h2 class="card-title">
      {{identity.software_name or 'Unknown'}} &mdash; v{{identity.software_version}}
      <span class="float-right">
        <code>{{identity.tag_id}}</code>
      </span>
    </h2>
    <table class="table card-text">
{% if identity.tag_version %}
      <tr class="row">
        <th class="col-2">Tag Version</th>
        <td class="col">{{identity.tag_version}}</td>
      </tr>
{% endif %}
{% if identity.summary %}
      <tr class="row">
        <th class="col-2">Summary</th>
        <td class="col">{{identity.summary}}</td>
      </tr>
{% endif %}
{% if identity.product %}
      <tr class="row">
        <th class="col-2">Product</th>
        <td class="col">{{identity.product}}</td>
      </tr>
{% endif %}
{% if identity.colloquial_version %}
      <tr class="row">
        <th class="col-2">Colloquial Version</th>
        <td class="col">{{identity.colloquial_version}}</td>
      </tr>
{% endif %}
{% if identity.revision %}
      <tr class="row">
        <th class="col-2">Revision</th>
        <td class="col">{{identity.revision}}</td>
      </tr>
{% endif %}
{% if identity.edition %}
      <tr class="row">
        <th class="col-2">Edition</th>
        <td class="col">{{identity.edition}}</td>
      </tr>
{% endif %}
{% for entity in identity.entities %}
      <tr class="row">
        <th class="col-2">Entity</th>
        <td class="col">
          <a href="https://{{entity.regid}}/">{{entity.name}}</a>
        </td>
        <td class="col-5">
{% for role in entity.roles %}
          <span class="badge badge-pill badge-primary">{{role.name}}</span>
{% endfor %}
        </td>
      </tr>
{% endfor %}
{% for link in identity.links %}
      <tr class="row">
        <th class="col-2">Link</th>
        <td class="col"><code>{{link.href}}</code></td>
        <td class="col-5"><code>{{link.rel}}</code></td>
      </tr>
{% endfor %}
    </table>
  </div>
</div>

{% endfor %}

{% endblock %}

lvfs/devices/templates/device.html
{% extends "default.html" %}
{% block title %}{{fws[0].md_prio.name if fws else 'No firmware for device found'}}{% endblock %}

{% block head %}
{% if fws|length > 0 %}
    <link rel="alternate" type="application/atom+xml"
      title="LVFS: {{fws[0].md_prio.name}}"
      href="{{url_for('devices.route_show_atom', appstream_id=appstream_id)}}" />
{% endif %}
{% endblock %}

{% block nav %}{% include 'device-nav.html' %}{% endblock %}

{% block content %}

{% if fws|length == 0 %}
<div class="card">
  <div class="card-body">
    <h2 class="card-title">Device Details</h2>
    <p class="card-text">No firmware is available for this device.</p>
  </div>
</div>

{% else %}

<div class="card">
  <div class="card-body">
    <h2 class="card-title">
      {{fws[0].vendor.display_name_with_team}} {{fws[0].md_prio.name}}
    </h2>
    <p class="card-text">{{fws[0].md_prio.description}}</p>
{% if fws[0].mds[0].is_eol %}
  <div class="alert alert-warning mt-1 card-text" role="alert">
    <strong>These devices are unlikely to get updates to fix critical security problems.</strong>
    The vendor has marked this device end-of-life and are no longer officially supported.
  </div>
{% endif %}
  </div>
</div>

{% for fw in fws %}
<a name="{{fw.version_display}}"></a>
<div class="card mt-3">
  <div class="card-body">
  <h2 class="card-title">Version {{fw.version_display}}:</h2>
{% if fw.remote.name == 'testing' %}
<p class="card-text">
  <b>Warning:</b> This firmware is in the testing state and may not be suitable for
  production systems.
</p>
{% endif %}
<div class="table card-text">
{% if fw.release_ts %}
  <div class="row">
    <div class="col col-sm-2 font-weight-bold">Released</div>
    <div class="col col-sm-10">{{fw.release_ts.strftime('%F %T')}}</div>
  </div>
{% endif %}
  <div class="row">
    <div class="col col-sm-2 font-weight-bold">State</div>
    <div class="col col-sm-10">{{fw.remote.name}}</div>
  </div>
  <div class="row">
    <div class="col col-sm-2 font-weight-bold">Urgency</div>
    <div class="col col-sm-10">{{fw.md_prio.release_urgency}}</div>
  </div>
  <div class="row">
    <div class="col col-sm-2 font-weight-bold">License</div>
    <div class="col col-sm-10">
{% if fw.md_prio.project_license.url %}
      <a href="{{fw.md_prio.project_license.url}}">{{fw.md_prio.project_license.name}}</a>
{% else %}
      {{fw.md_prio.project_license.name}}
{% endif %}
    </div>
  </div>
{% if fw.md_prio.requires_source_url %}
  <div class="row">
    <div class="col col-sm-2 font-weight-bold">Source</div>
    <div class="col col-sm-10">
      <a href="{{fw.md_prio.source_url}}">{{fw.md_prio.source_url}}</a>
    </div>
  </div>
{% endif %}
  <div class="row">
    <div class="col col-sm-2 font-weight-bold">Filename</div>
    <div class="col col-sm-10">
{% if fw.inhibit_download %}
      <p class="text-muted">
        The OEM that uploaded this firmware has chosen to disable downloads of
        the firmware when using a web browser.
        End users should use a client such as fwupdmgr to download and deploy
        the firmware.
      </p>
{% else %}
      <a href="{{fw.revisions[0].url}}">{{fw.original_filename}}</a>
{% endif %}
    </div>
  </div>
{% if fw.md_prio.release_descriptions %}
  <div class="row">
    <div class="col col-sm-2 font-weight-bold">Description</div>
    <div class="col col-sm-10">
      {{format_html_from_markdown(fw.md_prio.release_descriptions[0].value)|safe}}
{% if fw.md_prio.details_url_with_fallback %}
      <a class="btn" href="{{fw.md_prio.details_url_with_fallback}}">More details</a>
{% endif %}
    </div>
  </div>
{% endif %}
{% if fw.md_prio.issues %}
  <div class="row">
    <div class="col col-sm-2 font-weight-bold">Fixed issues:</div>
    <div class="col col-sm-10">
      <ul class="list-group mb-3">
{% for issue in fw.md_prio.issues %}
        <li class="list-group-item">
          <a class="btn" href="{{issue.url}}">{{issue.value_display}}</a>
{% if issue.description %}
          <p>{{issue.description}}</p>
{% endif %}
        </li>
{% endfor %}
      </ul>
    </div>
  </div>
{% endif %}
  <div class="row">
    <div class="col col-sm-2 font-weight-bold">Security</div>
    <div class="col col-sm-10">
      <ul class="list-group">
{% for claim in (fw.autoclaims+fw.claims)|sort() %}
        <li class="list-group-item">
          <img class="fa" src="{{url_for('cdn', filename='img/' + claim.icon_name + '-solid.svg')}}" width="22px" height="22px" />
          {{claim.summary}}
{% if claim.url %}
          <span class="float-right"><a class="btn btn-sm btn-outline-info" href="{{claim.url}}">More info</a></span>
{% endif %}
        </li>
{% endfor %}
{% if fw.md_prio.swids %}
        <li class="list-group-item">
          <img class="fa" src="{{url_for('cdn', filename='img/check-circle-solid.svg')}}" width="22px" height="22px" />
          Includes Software Bill of Materials
          <span class="float-right">
            <a class="btn btn-sm btn-outline-info" href="{{url_for('devices.route_swids', component_id=fw.md_prio.component_id)}}">
              More info
            </a>
          </span>
        </li>
{% endif %}
      </ul>
    </div>
  </div>
{% if fw.reports_verified %}
  <div class="row mt-3">
    <div class="col col-sm-2 font-weight-bold">Tested By</div>
    <div class="col col-sm-10">

      <ul class="list-group">
{% for rpt in fw.reports_verified %}
        <li class="list-group-item">
          <img class="fas" src="/uploads/{{rpt.user.vendor.icon}}" width="22px" height="22px" />
          {{rpt.verified_vendor.display_name}}
          <small>on {{rpt.verified_description}}</small>
          <span class="float-right">
            {{format_humanize_naturaltime(rpt.timestamp)}}
          </span>
        </li>
{% endfor %}
      </ul>
      <h6 class="text-muted mt-3">
        The vendors testing the update provide no warranty of any kind (express
        or implied), including but not limited to the warranties of merchantability,
        fitness for a particular purpose or non-infringement.
        In no event shall these vendors be liable for any claim, damages or
        other liability.
      </h6>
    </div>
  </div>
{% endif %}
</div>
{% if fw.md_prio.shards %}
    <a class="card-link btn btn-info" href="{{url_for('devices.route_shards', component_id=fw.md_prio.component_id)}}">Firmware Details</a>
{% if fw_previous[fw] %}
    <a class="card-link btn btn-info" href="{{url_for('devices.route_shards_diff',
                                                      component_id_old=fw_previous[fw].md_prio.component_id,
                                                      component_id_new=fw.md_prio.component_id)}}">Compare with previous</a>
{% endif %}
{% endif %}
  </div>
</div>

{% endfor %}

{% endif %}

{% endblock %}

lvfs/devices/templates/devicelist.html
{% extends "default.html" %}
{% block title %}Device List{% endblock %}

{% block content %}
<div class="card">
  <div class="card-body">
    <h2 class="card-title">Search for devices</h2>
    <form method="GET" class="form-inline" action="{{url_for('search.route_search')}}">
      <input type="hidden" name="csrf_token" value="{{csrf_token()}}"/>
      <div class="input-group">
        <input type="text" class="form-control" aria-label="search" id="value" name="value" required>
        <div class="input-group-append">
          <button class="input-group-text" type="submit">Search</button>
        </div>
      </div>
    </form>
  </div>
</div>

{% if vendors|length > 0 %}
<div class="card mt-3">
  <div class="card-body">
    <h2 class="card-title">Devices supported by the LVFS</h2>
    <p class="card-text">
      This list shows all the updates that have been made available to the public.
      This list is automatically generated and will be updated when new firmware
      is added or existing firmware is made available.
      Find the latest devices supported <a href="{{url_for('devices.route_new')}}">here</a>.
      For information about what vendors have been contacted about the LVFS,
      please see the <a href="{{url_for('main.route_vendorlist')}}">vendor engagement list</a>.
    </p>
  </div>
</div>
{% for vendor in vendors|sort(attribute='display_name_with_team') %}
{% if mds_by_vendor[vendor]|length > 0 %}
<a name="{{vendor.group_id}}"></a>
<div class="card mt-3">
  <div class="card-body">
    <h2 class="card-title">{{vendor.display_name_with_team}}</h2>
    <ul class="list-group">
{% for md in mds_by_vendor[vendor] %}
      <li class="list-group-item">
        <a href="{{url_for('devices.route_show', appstream_id=md.appstream_id)}}">{{md.name_with_category}}</a>
      </li>
{% endfor %}
    </ul>
{% if vendor.is_community %}
    <div class="alert alert-warning mt-3" role="alert">
      <strong>WARNING:</strong> This firmware is provided by LVFS community
      members and is not provided (or supported) by the original hardware vendor.
    </div>
{% endif %}
{% if vendor.missing_url %}
    <p class="card-text text-muted mt-3">
      If your {{vendor.display_name}} device is listed but missing a specific firmware update that
      you see on the vendor website, please <a href="{{vendor.missing_url}}">file an issue here</a>.
    </p>
{% endif %}
  </div>
</div>
{% endif %}
{% endfor %}
{% endif %}

{% endblock %}

lvfs/devices/templates/devices.html
{% extends "default.html" %}
{% block title %}Devices{% endblock %}

{% block content %}
<div class="card">
  <div class="card-body">
    <h2 class="card-title">Devices</h2>
{% for device in devices %}
<li><a href="{{url_for('devices.route_show', appstream_id=device)}}">{{device}}</a></li>
{% else %}
<p class="card-text">No devices to show!</p>
{% endfor %}
  </div>
</div>
{% endblock %}