lvfs/agreements/models.py
#!/usr/bin/python3
# -*- coding: utf-8 -*-
#
# Copyright (C) 2015 Richard Hughes <richard@hughsie.com>
#
# SPDX-License-Identifier: GPL-2.0+
#
# pylint: disable=too-few-public-methods

import datetime

from sqlalchemy import Column, Integer, Text, DateTime

from lvfs import db


class Agreement(db.Model):

    __tablename__ = "agreements"

    agreement_id = Column(Integer, primary_key=True)
    created = Column(DateTime, nullable=False, default=datetime.datetime.utcnow)
    version = Column(Integer, nullable=False)
    text = Column(Text, default=None)

lvfs/agreements/routes.py
#!/usr/bin/python3
# -*- coding: utf-8 -*-
#
# Copyright (C) 2018 Richard Hughes <richard@hughsie.com>
#
# SPDX-License-Identifier: GPL-2.0+

from flask import Blueprint, request, flash, url_for, redirect, render_template, g
from flask_login import login_required

from lvfs import db

from lvfs.util import admin_login_required

from .models import Agreement

bp_agreements = Blueprint("agreements", __name__, template_folder="templates")


@bp_agreements.route("/")
@bp_agreements.route("/<int:agreement_id>")
@login_required
def route_show(agreement_id=None):
    # find the right version
    if agreement_id:
        agreement = (
            db.session.query(Agreement)
            .filter(Agreement.agreement_id == agreement_id)
            .first()
        )
    else:
        agreement = (
            db.session.query(Agreement).order_by(Agreement.version.desc()).first()
        )
    if not agreement:
        agreement = Agreement(version=1, text="No agreement text found")
        db.session.add(agreement)
        db.session.commit()
    return render_template("agreement.html", category="admin", agreement=agreement)


@bp_agreements.route("/list")
@login_required
@admin_login_required
def route_list():

    # find the right version
    agreements = db.session.query(Agreement).all()
    return render_template(
        "agreement-list.html", category="admin", agreements=agreements
    )


@bp_agreements.route("/create", methods=["POST"])
@login_required
@admin_login_required
def route_create():

    # create something
    agreement = Agreement(version=1, text="New agreement text")
    db.session.add(agreement)
    db.session.commit()
    flash("Created agreement")
    return redirect(
        url_for("agreements.route_modify", agreement_id=agreement.agreement_id)
    )


@bp_agreements.route("/<int:agreement_id>/accept", methods=["POST"])
@login_required
def route_confirm(agreement_id):

    # find the object for the ID
    agreement = (
        db.session.query(Agreement)
        .filter(Agreement.agreement_id == agreement_id)
        .first()
    )
    if not agreement:
        flash("No agreement ID found", "warning")
        return redirect(url_for("agreements.route_show"))

    # already agreed to a newer version
    if g.user.agreement and g.user.agreement.version >= agreement.version:
        flash("You already agreed to this version of the agreement", "info")
        return redirect(url_for("agreements.route_show"))

    # save this
    g.user.agreement_id = agreement.agreement_id
    db.session.commit()
    flash("Recorded acceptance of the agreement")
    return redirect(url_for("upload.route_firmware"))


@bp_agreements.route("/decline", methods=["POST"])
@bp_agreements.route("/<int:agreement_id>/decline", methods=["POST"])
@login_required
def route_decline(agreement_id=None):
    g.user.agreement_id = None
    db.session.commit()
    flash("Recorded decline of the agreement %i" % agreement_id)
    return redirect(url_for("main.route_index"))


@bp_agreements.route("/<int:agreement_id>/modify", methods=["GET", "POST"])
@login_required
@admin_login_required
def route_modify(agreement_id):

    # match
    agreement = (
        db.session.query(Agreement)
        .filter(Agreement.agreement_id == agreement_id)
        .first()
    )
    if not agreement:
        flash("No agreement with that ID", "danger")
        return redirect(url_for("agreements.route_list"))

    # view
    if request.method != "POST":
        return render_template(
            "agreement-admin.html", category="admin", agreement=agreement
        )

    # change
    if "version" in request.form:
        agreement.version = int(request.form["version"])
    if "text" in request.form:
        agreement.text = request.form["text"]
    db.session.commit()
    flash("Modified agreement")
    return redirect(url_for("agreements.route_modify", agreement_id=agreement_id))


@bp_agreements.route("/<int:agreement_id>/delete", methods=["POST"])
@login_required
@admin_login_required
def route_delete(agreement_id):

    # match
    agreement = (
        db.session.query(Agreement)
        .filter(Agreement.agreement_id == agreement_id)
        .first()
    )
    if not agreement:
        flash("No agreement with that ID", "danger")
        return redirect(url_for("agreements.route_list"))

    # change
    db.session.delete(agreement)
    db.session.commit()
    flash("Deleted agreement")
    return redirect(url_for("agreements.route_list"))

lvfs/agreements/templates/agreement-admin.html
{% extends "default.html" %}
{% block title %}Legal Agreement{% endblock %}

{% block content %}
<div class="card">
  <div class="card-body">
    <h2 class="card-title">Legal Agreement</h2>
<form method="post" action="{{url_for('agreements.route_modify', agreement_id=agreement.agreement_id)}}">
  <input type="hidden" name="csrf_token" value="{{csrf_token()}}"/>
  <div class="form-group">
    <label for="version">Version (incrementing will prompt users):</label>
    <input type="number" class="form-control" id="version" name="version" value="{{agreement.version}}" required>
  </div>
  <div class="form-group">
    <label for="text">Markup in HTML format:</label>
    <textarea class="form-control" id="text" name="text" cols="100" rows="25">{{agreement.text}}</textarea>
  </div>
  <input type="submit" class="btn btn-primary" value="Save">
</form>
<form action="{{url_for('agreements.route_delete', agreement_id=agreement.agreement_id)}}" method="POST">
  <input type="hidden" name="csrf_token" value="{{csrf_token()}}"/>
  <button class="btn btn-danger">Delete</button>
</form>
  </div>
</div>

{% endblock %}

lvfs/agreements/templates/agreement-list.html
{% extends "default.html" %}
{% block title %}Agreement List{% endblock %}

{% block content %}
{% if agreements|length > 0 %}
<div class="card">
  <div class="card-body">
    <h2 class="card-title">Agreement List</h2>
<table class="table">
  <tr class="row table-borderless">
    <th class="col col-sm-2">Created</th>
    <th class="col col-sm-1">Version</th>
    <th class="col col-sm-7">Text</th>
    <th class="col col-sm-2">&nbsp;</th>
  </tr>
{% for u in agreements|sort(attribute='created',reverse=True) %}
  <tr class="row">
    <td class="col col-sm-2">{{u.created.strftime('%F %T')}}</td>
    <td class="col col-sm-1">{{u.version}}</td>
    <td class="col col-sm-7">{{u.text|truncate(300, False, '…')}}</td>
    <td class="col col-sm-2">
      <a class="btn btn-info btn-block" href="{{url_for('agreements.route_modify', agreement_id=u.agreement_id)}}">Details</a>
    </td>
  </tr>
{% endfor %}
  <tr class="row">
    <td class="col col-sm-2"></td>
    <td class="col col-sm-1"></td>
    <td class="col col-sm-7"></td>
    <td class="col col-sm-2">
      <form action="{{url_for('agreements.route_create')}}" method="POST">
        <input type="hidden" name="csrf_token" value="{{csrf_token()}}"/>
        <button class="btn btn-info btn-block">Create</button>
      </form>
    </td>
  </tr>
</table>
  </div>
</div>
{% else %}
<div class="card">
  <div class="card-body">
    <p class="card-text text-secondary">
      No agreements defined.
    </p>
  </div>
</div>
{% endif %}

{% endblock %}

lvfs/agreements/templates/agreement.html
{% extends "default.html" %}
{% block title %}Legal Agreement{% endblock %}

{% block content %}
<div class="card">
  <div class="card-body">
    <h2 class="card-title">Legal Agreement</h2>
{{agreement.text|safe}}
    <p class="text-muted mt-3">Version {{agreement.version}}</p>
    <div class="text-center">
      <form action="{{url_for('agreements.route_confirm', agreement_id=agreement.agreement_id)}}" method="POST">
        <input type="hidden" name="csrf_token" value="{{csrf_token()}}"/>
        <button class="btn btn-primary btn-lg">Agree</button>
      </form>
      <form action="{{url_for('agreements.route_decline', agreement_id=agreement.agreement_id)}}" method="POST">
        <input type="hidden" name="csrf_token" value="{{csrf_token()}}"/>
        <button class="btn btn-danger btn-lg mt-3">Decline</button>
      </form>
    </div>
  </div>
</div>

{% endblock %}